### ISSUE TITLE
make ipc crashes

### ISSUE THREAD

**Issue by korken89** [cpavlina/kicad-pcblib#7]
Hi, using your script with python 3.5 crashes with the following error:

```
Generating KiCad library...
Traceback (most recent call last):
  File "download_ipc.py", line 192, in <module>
    main ()
  File "download_ipc.py", line 154, in main
    main_2 (args, tempdir, ipc_zip)
  File "download_ipc.py", line 189, in main_2
    freepcb2kicad.main (fpargs, zipfile=zipfile)
  File "freepcb2pretty.py", line 807, in main
    SexpDump (sexp, f)
  File "freepcb2pretty.py", line 91, in SexpDump
    SexpDump (i, f, indentlevel + 1)
  File "freepcb2pretty.py", line 94, in SexpDump
    elif isinstance (sexp, (str, unicode)):
NameError: name 'unicode' is not defined
```

Hope you can fix it, thanks!

**Comment by cpavlina** [comment]
No need to run this script anymore, I've included its generated output. I'll look at this though.
